"""added datetime updated

Revision ID: bc7b3c74a773
Revises: 7f30abb21e82
Create Date: 2026-07-04 16:49:39.835138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7b3c74a773'
down_revision: Union[str, Sequence[str], None] = '7f30abb21e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('datetime_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'datetime_updated')
    # ### end Alembic commands ###
